server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mike6321/TIL
#          uri: file:///Users/nhn/IdeaProjects/repository/TIL
